/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.myorg.codeCoach;

import javax.swing.JFrame;

/**
 *
 * @author JoycePC
 */
public class CodeCoachPanel extends javax.swing.JPanel {

    /**
     * Creates new form CodeCoachPanel
     */
    public CodeCoachPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataProcess = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        CodeCoachIcon = new javax.swing.JToggleButton();
        menuItem = new javax.swing.JButton();

        dataProcess.setMaximumSize(new java.awt.Dimension(200, 200));
        dataProcess.setMinimumSize(new java.awt.Dimension(200, 200));
        dataProcess.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\e014hp\\Desktop\\processing.gif")); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CodeCoachPanel.class, "CodeCoachPanel.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout dataProcessLayout = new javax.swing.GroupLayout(dataProcess.getContentPane());
        dataProcess.getContentPane().setLayout(dataProcessLayout);
        dataProcessLayout.setHorizontalGroup(
            dataProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dataProcessLayout.setVerticalGroup(
            dataProcessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CodeCoachIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\e014hp\\Desktop\\Coach_Hat_tn.jpg")); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(CodeCoachIcon, org.openide.util.NbBundle.getMessage(CodeCoachPanel.class, "CodeCoachPanel.CodeCoachIcon.text")); // NOI18N
        CodeCoachIcon.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/org/myorg/codeCoach/code24.png"))); // NOI18N
        CodeCoachIcon.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/myorg/codeCoach/icon24.png"))); // NOI18N
        CodeCoachIcon.setIconTextGap(0);
        CodeCoachIcon.setMaximumSize(new java.awt.Dimension(33, 33));
        CodeCoachIcon.setMinimumSize(new java.awt.Dimension(33, 33));
        CodeCoachIcon.setPreferredSize(new java.awt.Dimension(33, 33));
        CodeCoachIcon.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\e014hp\\Desktop\\icon-technology.png")); // NOI18N
        CodeCoachIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeCoachIconActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(CodeCoachIcon);

        menuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\e014hp\\Desktop\\downarrow16.png")); // NOI18N
        menuItem.setAlignmentY(0.0F);
        menuItem.setLabel(org.openide.util.NbBundle.getMessage(CodeCoachPanel.class, "CodeCoachPanel.menuItem.label")); // NOI18N
        menuItem.setMaximumSize(new java.awt.Dimension(16, 16));
        menuItem.setMinimumSize(new java.awt.Dimension(16, 16));
        menuItem.setPreferredSize(new java.awt.Dimension(16, 16));
        menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(menuItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void activityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activityButtonActionPerformed
        // TODO add your handling code here:
        dataProcess.show();
    }//GEN-LAST:event_activityButtonActionPerformed

    private void menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemActionPerformed

    private void CodeCoachIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeCoachIconActionPerformed
        dataProcess.show();
    }//GEN-LAST:event_CodeCoachIconActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CodeCoachIcon;
    private javax.swing.JFrame dataProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton menuItem;
    // End of variables declaration//GEN-END:variables
}
