/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.myorg.codeCoach;

/**
 *
 * @author JoycePC
 */
public class stopActDialog extends javax.swing.JDialog {
    public String status;
    /**
     * Creates new form stopActDialog
     */
    public stopActDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.status="end";
        setLocationRelativeTo(parent);  
        setTitle("Code Coach Status");
        setSize(476,260);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        infoText = new javax.swing.JLabel();
        getBackButton = new javax.swing.JButton();
        stopCoachingButton = new javax.swing.JButton();
        jLabel_endIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel_titulo.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel_titulo, org.openide.util.NbBundle.getMessage(stopActDialog.class, "stopActDialog.jLabel_titulo.text")); // NOI18N
        getContentPane().add(jLabel_titulo);
        jLabel_titulo.setBounds(150, 20, 158, 30);

        infoText.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        infoText.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(infoText, org.openide.util.NbBundle.getMessage(stopActDialog.class, "stopActDialog.infoText.text")); // NOI18N
        infoText.setToolTipText(org.openide.util.NbBundle.getMessage(stopActDialog.class, "stopActDialog.infoText.toolTipText")); // NOI18N
        infoText.setDoubleBuffered(true);
        infoText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(infoText);
        infoText.setBounds(20, 60, 430, 33);

        getBackButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\e014hp\\Documents\\NetBeansProjects\\Code-Coach\\icon\\aundo.png")); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(getBackButton, org.openide.util.NbBundle.getMessage(stopActDialog.class, "stopActDialog.getBackButton.text")); // NOI18N
        getBackButton.setToolTipText(org.openide.util.NbBundle.getMessage(stopActDialog.class, "stopActDialog.getBackButton.toolTipText")); // NOI18N
        getBackButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(getBackButton);
        getBackButton.setBounds(20, 110, 130, 40);

        stopCoachingButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\e014hp\\Documents\\NetBeansProjects\\Code-Coach\\icon\\cancel.png")); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(stopCoachingButton, org.openide.util.NbBundle.getMessage(stopActDialog.class, "stopActDialog.stopCoachingButton.text")); // NOI18N
        stopCoachingButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stopCoachingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopCoachingButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stopCoachingButton);
        stopCoachingButton.setBounds(160, 140, 120, 40);

        jLabel_endIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\e014hp\\Documents\\NetBeansProjects\\Code-Coach\\icon\\endIcon.png")); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel_endIcon, org.openide.util.NbBundle.getMessage(stopActDialog.class, "stopActDialog.jLabel_endIcon.text")); // NOI18N
        getContentPane().add(jLabel_endIcon);
        jLabel_endIcon.setBounds(290, 90, 180, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\e014hp\\Documents\\NetBeansProjects\\Code-Coach\\icon\\background.png")); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(stopActDialog.class, "stopActDialog.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBackButtonActionPerformed
        // TODO add your handling code here:
        this.status="back";
        setVisible(false);
    }//GEN-LAST:event_getBackButtonActionPerformed

    private void stopCoachingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopCoachingButtonActionPerformed
        // TODO add your handling code here:
        this.status="end";
        setVisible(false);
    }//GEN-LAST:event_stopCoachingButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stopActDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stopActDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stopActDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stopActDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                stopActDialog dialog = new stopActDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getBackButton;
    private javax.swing.JLabel infoText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_endIcon;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JButton stopCoachingButton;
    // End of variables declaration//GEN-END:variables
}
